version: "3.5"

networks:
  alertmanager:
  alertmanager-private:

volumes:
  alertmanager:

services:
  ingress:
    networks:
      - alertmanager

  alertmanager:
    environment:
      - SLACK_URL=https://hooks.slack.com/services/TOKEN
      - SLACK_CHANNEL=devops-alerts
      - SLACK_USER=alertmanager
    image: stefanprodan/swarmprom-alertmanager:v0.14.0
    networks:
      - alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    volumes:
      - alertmanager:/alertmanager
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      labels:
        - com.ouroboros.enable=true
        - traefik.frontend.rule=$ALERTMANAGER_ROUTING_LABEL
        - traefik.frontend.priority=$ALERTMANAGER_ROUTING_LABEL_PRIORITY
        - traefik.port=9093
        - ${TRAEFIK_BASIC_AUTH}
        - traefik.enable=true
        - traefik.tags=ingress
        - traefik.docker.network=${STACK_NAME:-technocore}_alertmanager
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https

  unsee:
    image: cloudflare/unsee:v0.8.0
    networks:
      - alertmanager
    environment:
      - "ALERTMANAGER_URIS=default:http://alertmanager:9093"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - com.ouroboros.enable=true
        - traefik.frontend.rule=$UNSEE_ROUTING_LABEL
        - traefik.frontend.priority=$UNSEE_ROUTING_LABEL_PRIORITY
        - ${TRAEFIK_BASIC_AUTH}
        - traefik.enable=true
        - traefik.port=8080
        - traefik.tags=ingress
        - traefik.docker.network=${STACK_NAME:-technocore}_alertmanager
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
 